sequenceDiagram
    actor Customer
    participant FE as Front-end
    participant BE as Back-end
    participant PG as Payment Gateway

    Customer ->> FE: Open website
    activate FE
    Customer ->> FE: Add products to cart
    Customer ->> FE: Proceed to checkout page
    Customer ->> FE: Enter payment and shipping details
    Customer ->> FE: Confirm details
    FE ->> BE: Send order details
    activate BE

    alt Payment denied
        BE ->> PG: Send payment details
        activate PG
        PG -->> BE: Payment denied
        deactivate PG
        BE -->> FE: Send error object
        FE -->> Customer: Display error page
    else Payment authorized
        BE ->> PG: Send payment details
        activate PG
        PG -->> BE: Payment authorized
        deactivate PG
        create participant Order as :Order
        BE ->> Order: <create new Order>
        create participant Invoice as :Invoice
        Order ->> Invoice: <create new Invoice>

        BE ->>+ Order: Save to DB
        Order ->> DB: Send own details
        activate DB; deactivate DB
        Order ->>+ Invoice: Save to DB
        Invoice ->> DB: Send own details
        activate DB; deactivate DB
        Invoice -->>- Order: (saved)
        Order -->>- BE: (saved)
        BE -->>- FE: Send Order and Invoice details
        FE -->> Customer: Display Order and Invoice details
    end

    Customer ->> FE: Close website
    deactivate FE

    participant DB as Database
