sequenceDiagram
    actor Customer
    participant FE as Front-end
    participant BE as Back-end

    Customer ->> FE: Open website
    activate FE
    Customer ->> FE: Go to the sign up page
    Customer ->> FE: Enter details
    FE ->> BE: Forward user entered details
    activate BE
    alt Email is in use
        BE ->> DB: Check if email is used
        activate DB
        DB -->> BE: Email is in use
        deactivate DB
        BE -->> FE: Email is in use
        FE -->> Customer: Display error page
    else Email is available
        BE ->> DB: Check if email is used
        activate DB
        DB -->> BE: Email is available
        deactivate DB
        create participant CustomerObj as :Customer
        BE ->> CustomerObj: <create new Customer>
        BE ->>+ CustomerObj: Save to DB
        CustomerObj ->>- DB: Send own details
        activate DB
        deactivate DB
        BE -->>- FE: Success
        FE -->> Customer: Display success page
    end
    Customer ->> FE: Close website
    deactivate FE

    participant DB as Database
