sequenceDiagram
    box transparent Unprivileged client context
        actor Customer
        participant FE as Front-end
    end
    box transparent Privileged server context
        participant BE as Back-end
        participant DB as Database
    end

    alt Valid session token
        Customer ->>+ FE: Action
        FE ->> BE: HTTP request
        activate BE
        BE ->> DB: Check if session is valid
        activate DB
        DB -->> BE: Session is valid
        deactivate DB
        BE ->> BE: Handle request
        BE -->> FE: HTTP response
        deactivate BE
        FE ->> FE: Handle response
        FE -->> Customer: Show new or modified page
        deactivate FE
    else Invalid token
        Customer ->>+ FE: Action
        FE ->> BE: HTTP request
        activate BE
        BE ->> DB: Check if session is valid
        activate DB
        DB -->> BE: Session is invalid or expired
        deactivate DB
        note over BE: The request is not handled.
        BE -->> FE: HTTP 403 Response
        deactivate BE
        FE -->> Customer: Render login page
        deactivate FE
    end
