stateDiagram

    [*] --> COLLECTING_PRODUCTS
    COLLECTING_PRODUCTS --> READY_FOR_SHIPPING
    READY_FOR_SHIPPING --> SHIPPED
    SHIPPED --> DELIVERED
    DELIVERED --> [*]
    DELIVERED --> RETURNED
    RETURNED --> [*]

    COLLECTING_PRODUCTS --> CANCELLED
    READY_FOR_SHIPPING --> CANCELLED
    CANCELLED --> [*]
